import React from "react";

function About() {
  return (
    <div>
        <h1>ABOUT!</h1>
        <p>ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! ABOUT! </p>
    </div>
    
  );
}

export default About;